version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directories:
      - "/"
      - "/requirements/*"
    schedule:
      interval: "monthly"
    groups:
      python-dependencies:
        patterns:
          - "*"
