ci:
  autofix_prs: true
  autoupdate_schedule: monthly
  skip: [pylint, deptry, mypy]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v6.0.0'
    hooks:
    - id: check-ast
    - id: check-case-conflict
    - id: check-symlinks
    #- id: check-xml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace
      exclude: setup.cfg
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.15.20'
    hooks:
      - id: ruff
        args: [--fix]
        files: ^(async_upnp_client|tests)/.+\.py$
      - id: ruff-format
        files: ^(async_upnp_client|tests)/.+\.py$
  - repo: https://github.com/codespell-project/codespell
    rev: 'v2.4.2'
    hooks:
      - id: codespell
        args:
          - --skip="./.*,*.csv,*.json"
          - --quiet-level=2
        exclude_types: [csv, json]
        files: ^(async_upnp_client|tests)/.+\.py$
  - repo: https://github.com/PyCQA/pylint
    rev: 'v4.0.6'
    hooks:
      - id: pylint
        additional_dependencies:
          - pytest~=9.0.2
          - voluptuous~=0.16.0
          - aiohttp>3.9.0,<4.0
          - python-didl-lite~=1.5.0
          - defusedxml~=0.7.1
          - pytest-asyncio >= 1.0,< 1.4
          - pytest-aiohttp >=1.0.5,<1.2.0
        files: ^(async_upnp_client|tests)/.+\.py$
  - repo: https://github.com/fpgmaas/deptry
    rev: '0.25.1'
    hooks:
      - id: deptry
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v2.1.0'
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies:
          - python-didl-lite~=1.5.0
          - pytest~=9.0.2
          - aiohttp~=3.13.3
          - pytest-asyncio >= 1.0,< 1.4
          - pytest-aiohttp >=1.0.5,<1.2.0
        files: ^(async_upnp_client|tests)/.+\.py$
