[tox]
envlist = py310, py311, py312, py313, py314, ruff, pylint, codespell, mypy, deptry

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312, ruff, pylint, codespell, mypy, deptry
    3.13: py313
    3.14: py314

[testenv]
commands = py.test --cov=async_upnp_client --cov-report=term --cov-report=xml:coverage-{env_name}.xml {posargs}
ignore_errors = True
deps =
    pytest == 9.0.2
    aiohttp ~= 3.13.3
    pytest-asyncio >= 1.0,< 1.4
    pytest-aiohttp >=1.0.5,<1.2.0
    pytest-cov >= 7.0,< 7.1
    coverage >= 7.13,< 7.14

[testenv:ruff]
basepython = python3
ignore_errors = True
deps =
    ruff == 0.15.1
commands =
    ruff check async_upnp_client tests
    ruff format --check async_upnp_client tests

[testenv:pylint]
basepython = python3
ignore_errors = True
deps =
    pylint == 4.0.4
    pytest ~= 9.0.2
    pytest-asyncio >= 1.0,< 1.4
    pytest-aiohttp >=1.0.5,<1.2.0
commands = pylint async_upnp_client tests

[testenv:codespell]
basepython = python3
ignore_errors = True
deps =
    codespell == 2.4.1
commands = codespell async_upnp_client tests

[testenv:mypy]
basepython = python3
ignore_errors = True
deps =
    mypy == 1.19.1
    python-didl-lite ~= 1.5.0
    pytest ~= 9.0.2
    aiohttp ~= 3.13.3
    pytest-asyncio >= 1.0,< 1.4
    pytest-aiohttp >=1.0.5,<1.2.0
commands = mypy --ignore-missing-imports async_upnp_client tests

[testenv:deptry]
basepython = python3
ignore_errors = True
deps =
    deptry == 0.24.0
commands = deptry async_upnp_client
