[tox]
envlist = py39, py310, py311, py312, py313, flake8, pylint, codespell, mypy, black, isort

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312, flake8, pylint, codespell, mypy, black, isort
    3.13: py313

[testenv]
commands = py.test --cov=async_upnp_client --cov-report=term --cov-report=xml:coverage-{env_name}.xml {posargs}
ignore_errors = True
deps =
    pytest == 8.3.3
    aiohttp ~= 3.10.9
    pytest-asyncio >= 0.24,< 0.26
    pytest-aiohttp >=1.0.5,<1.2.0
    pytest-cov >= 5.0,< 6.1
    coverage >=7.6.1,<7.8.0
    asyncmock ~= 0.4.2

[testenv:flake8]
basepython = python3
ignore_errors = True
deps =
    flake8 == 7.1.1
    flake8-docstrings ~= 1.7.0
    pydocstyle ~= 6.3.0
commands = flake8 async_upnp_client tests

[testenv:pylint]
basepython = python3
ignore_errors = True
deps =
    pylint == 3.3.1
    pytest ~= 8.3.3
    pytest-asyncio >= 0.24,< 0.26
    pytest-aiohttp >=1.0.5,<1.2.0
commands = pylint async_upnp_client tests

[testenv:codespell]
basepython = python3
ignore_errors = True
deps =
    codespell == 2.3.0
commands = codespell async_upnp_client tests

[testenv:mypy]
basepython = python3
ignore_errors = True
deps =
    mypy == 1.11.2
    python-didl-lite ~= 1.4.0
    pytest ~= 8.3.3
    aiohttp ~= 3.10.9
    pytest-asyncio >= 0.24,< 0.26
    pytest-aiohttp >=1.0.5,<1.2.0
commands = mypy --ignore-missing-imports async_upnp_client tests

[testenv:black]
basepython = python3
ignore_errors = True
deps =
    black == 24.8.0
commands = black --diff async_upnp_client tests

[testenv:isort]
basepython = python3
ignore_errors = True
deps =
    isort == 5.13.2
commands = isort --check-only --diff --profile=black async_upnp_client tests
