name: Build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
        python -m pip install --upgrade tox tox-gh-actions
    - name: Test with tox
      run: tox
    - name: Build package
      run: python -m build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions-${{ matrix.python-version }}
        path: dist/
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      if: ${{ hashFiles('coverage-py312.xml') != '' }}
      with:
        files: coverage-py312.xml
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  markdown_lint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: '**/*.md'
